### ISSUE TITLE
unlimited time dimension

### ISSUE THREAD

**Issue by adagj** [AleksiNummelin/BLOM_utils#1]
Hi,
you probably have considered this already, but will it be possible to add 
data.createDimension('time', None) before saving the dataset in order to set time to unlimited?

Cheers,
Ada

**Comment by AleksiNummelin** [comment]
I've did play a bit with the time dimension, but I remember that I didn't manage to make anything work, but I can try this to see if it does the trick.

**Comment by AleksiNummelin** [comment]
This is fixed by the latest commit.
